### ISSUE TITLE
Feature: Generate TODO file containing results

### ISSUE THREAD

**Issue by Jalkhov** [dodget/python-todo-comments#1]
A parameter for generate a file with results would be nice, and, maybe improve a little the output formatting, like this:

![imagen](https://user-images.githubusercontent.com/36505934/175858371-173bcc5e-2a2e-4eb6-bdd4-80d2e3de26d0.png)

BTW, nice plugin, simple and usefull <3

**Comment by dodget** [comment]
Good ideas, I'll get around to it this week hopefully

**Comment by dodget** [comment]
So, I guess I had the output file option already available, but the README wasn't up-to-date. Just updated the docs. You can specify the output file with the `-o` or `--output` argument. I'll get around to the reformatting on the weekend

**Comment by dodget** [comment]
I just published a version on pypi with improved formatting. Closing this. Thanks for the feedback
